services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: permissions-postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
# healthcheck:
#   test: [ "CMD-SHELL", "pg_isready -U ${DB_NAME}" ]
#   interval: 10s
#   retries: 5
#   start_period: 30s
#   timeout: 5s

volumes:
  pgdata: